### PR TITLE
chore: add error dsns

### LINKED ISSUE #1680: [FEATURE] Integrate glitchtip for za and tz deployments
**What?**
Follow-up from https://github.com/IDEMSInternational/parenting-app-ui/pull/1667

- [x] Decide whether to self-host glitchtip instance or rely on paid/free hosted tier (free allows 1000 error logs per month)
- [x] Add dsn to deployment configs
- [x] Communicate as required any changes to data policies (depending on where the service ends up being hosted)

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)
- [ ] **Privacy Policy / T&Cs updated**

## Description
- Integrate glitchtip for TZ and ZA deployments
- Add additional URL pathname (e.g. /template/home_screen) to firebase crashlytics logs

## Review Notes
Please double check the DSN I added match those on the glitchtip project pages
https://app.glitchtip.com/idems/projects

Additionally, I've emailed Elena separately to inform of the data provider, we may want to wait for a response before merging/releasing next version with this in

## Git Issues

Closes #1680

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

### CODE REVIEW

**Review by jfmcquade — APPROVED** [review]
Looks good, the DSNs do seem to match the appropriate projects on glitchtip

**Comment by chrismclarke** [comment]
Thanks @jfmcquade , I'll leave it to @EsmeeIDEMS to merge pending confirmation of upcoming release and required policy updates

**Comment by esmeetewinkel** [comment]
@chrismclarke I'm not sure how to deal with merge conflicts here. Trying to update with current `master` but I can't since I have local changes. However, whenever I delete the locally changed files they reappear a second later. 

image

**Comment by chrismclarke** [comment]
Glad you were able to get things working @esmeetewinkel , I had a similar issue a while back so not related specifically to this PR but some recent git file storage changes (original [slack thread](https://idems-international.slack.com/archives/C02AB6E7F0F/p1674880073451459))

**Comment by chrismclarke** [comment]
@esmeetewinkel - feel free to merge whenever you are happy that the policy changes are in

**Pull request merged**
