### PR TITLE
feat: add support for dynamic notifications

### LINKED ISSUE #1248: [FEATURE] Notification schedule should read from fields and perform calculations
**What?**
- [x] Notification schedules should read from fields, e.g. the value `+@fields.workshop_start_day` in the `schedule.day_of_week` column should work.
- [x] Notification schedules should be able to perform simple javascript calculations. In particular, the `schedule.day_of_week` column needs to be able to compute `(+@fields.workshop_start_day +3)%7`
- [x] Campaign `activation_condition_list` should be able to do `<= @fields.some_integer` conditions

**How?**
Statements that need to be computed could start with `@calc` if that's useful in any way. 

**Template**
[nf_schedule_in_week_messages](https://docs.google.com/spreadsheets/d/1JXb0lzz8Hztl6K4_3zaUpYrpq9XJjTO7YRPAsx03F-4/edit#gid=513586624)

image

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

## Description

- Add support for dynamic content throughout notifications via `@` syntax (e.g. @fields, @global etc.). Previously only support had been added for notification title/text, now includes activation conditions and scheduling.

## Author Notes
Notification conditions can now be authored in standard way (`@fields.some_field === some_value`) instead of legacy (`get_field | some_field : some_value`). This also means additional comparisons can be done (previously only equals).

In order to preserve compatibility with the (now legacy) notifications authoring syntax, any condition without a `|` character will be presumed part of the new system and any with part of the old. Eventually we should replace all cases of `get_field | some_field : some_value` with `@fields.some_field === some_value` - when this has been done I can tidy up the code that handles the temporary workaround. 

## Dev Notes
Whilst the `@fields` can now replace the `get_field` syntax we can't fully get rid of the legacy notifications condition processing system as we have no replacement for database queries. We first need to define an authoring syntax to wrap around possible querying structures, implement (via `@db` or similar) and then complete replacement. Raised in https://github.com/IDEMSInternational/parenting-app-ui/issues/1256

## Review Notes
I made temporary changes to [notifications_in_week_messages](https://docs.google.com/spreadsheets/d/1JXb0lzz8Hztl6K4_3zaUpYrpq9XJjTO7YRPAsx03F-4/edit#gid=513586624) (to match comments) for testing (see video below) but have since reverted back - so will need to checkout, update and sync local to test further. See video below for first test, I also checked `'(+@fields.workshop_start_day +2)%7` and was working, but worth giving quick functional test also, possibly with foreign language to confirm translations working as expected.

Ideally we should add to the example notifications to add a clear example of using dynamic content, however it seemed a bit much for me to do whilst developing as would likely involve some means of showing what campaigns are scheduled as well as ability to change fields.

## Git Issues

Closes #1248

## Screenshots/Videos

Notification scheduling change depending on field

https://user-images.githubusercontent.com/10515065/155249139-cfa1f0ff-e792-4a33-a684-15871589ad3d.mp4

### CODE REVIEW

**Comment by EsmeeIDEMS** [comment]
The dynamic conditions seem to work well on a sheet that is a `notification_schedule`, but not on `campaign_rows`. 

Examples of what I need are authored in [nf_w_self_care](https://docs.google.com/spreadsheets/d/1JXb0lzz8Hztl6K4_3zaUpYrpq9XJjTO7YRPAsx03F-4/edit#gid=375185493). 

Debug examples of this are authored in the campaign debug_condition which corresponds to the sheet [debug_campaign_rows_cond](https://docs.google.com/spreadsheets/d/1Jf38D4pkoBO0QIUcw1IFAqlEokrUzhOESi3hNlW0vZM/edit#gid=2092469363). 
However, when this sheet is marked as released in the content list, all debug campaigns scheduled in [debug_campaign_schedules](https://docs.google.com/spreadsheets/d/1Jf38D4pkoBO0QIUcw1IFAqlEokrUzhOESi3hNlW0vZM/edit#gid=998700467) disappear from my campaign debugger (see screenshot)
image

I was wondering whether we should stick to `(de)activation_condition_list` with list separator `;` which means OR in one case and AND in the other, or we should name the column`(de)activation_condition` and use the syntax `||` and `&&` as we do in the `condition` column for template.

**Comment by chrismclarke** [comment]
Latest updates - should now all be working as intended

https://user-images.githubusercontent.com/10515065/157746403-62f183ca-c34e-4862-b836-1029cc50787a.mp4

**Review by EsmeeIDEMS — CHANGES_REQUESTED** [review]
The conditions seem to be working well now, thanks! 

Only remaining issues I can find are 
1. Translations of notifications no longer work
2. Evaluation of `@global` in notifications no longer works
Both of these do work on master. 

Screenshot on this branch (after syncing content, I made some minor edits to demo): 
image

Screenshot on master branch (working correctly): 
image

**Comment by chrismclarke** [comment]
Ok, should now be fixed
image

**Review by EsmeeIDEMS — APPROVED** [review]

**Comment by EsmeeIDEMS** [comment]
Closes #908

**Pull request merged**
