### PR TITLE
Fix radio button size issue

### LINKED ISSUE #1014: [BUG] Radio button size improvements
**Describe the bug**
- [ ] The size of the buttons in a radio group changes depending on whether or not the parameter options_per_row is given. Desired behaviour: A set of _n_ radio buttons that fit on one row should not change if parameter options_per_row is set to _n_. 
- [ ] Radio buttons should increase in size to fit the text. 

**App version**
v0.11.2

**To Reproduce**
Open debug template. 

**Debug Template**
[debug_radio_group_size](https://docs.google.com/spreadsheets/d/1pSFFOv9B9x0oUSuSJDp6RNePJ1XSP6yVSjXA8jzBclQ/edit#gid=481972108)

**Screenshots and videos**
image

### PR DESCRIPTION
**Pull request by thisishamza**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

## Description

Fixes the radio button size issues.Now, the button size is adjusted according to the size of text inside it.

## Git Issues

Closes #1014 

## Screenshots/Videos

debug_radio_group_size_ss

### CODE REVIEW

**Review by EsmeeIDEMS — CHANGES_REQUESTED** [review]
This addresses the second issue in #1014, but not the first. Would it be possible for these two sets of radio buttons to look the same (i.e. same width and font size)?
image
image

**Comment by EsmeeIDEMS** [comment]
Not sure if this is problematic, but there seems to be a problem with the build: 
image

**Comment by zulkifelff** [comment]
@EsmeeIDEMS 

https://idems-international.slack.com/archives/C02AB6E7F0F/p1637447383011300

**Review by chrismclarke — COMMENTED** [review]
The first part of the fix is good to remove use of scale factors so text fits naturally, however there are many more changes required to fix this component, namely:

- Replace flex with grid layout, exposing param for min content width
- removing all hardcoded sizes
- tidying class names
- refactoring to plh CSS overrides

I'm going to re-assign the issue to myself as I'm implementing similar changes elsewhere and close here

**Pull request closed without merging**
