### PR TITLE
feat: add 3 new variants for display group: box_gray, box_primary, box_secondary

### LINKED ISSUE #2149: [FEATURE] New display group variant - neutral grey
**What?**
A new variant/style for the display group that looks like the box in the attached image

Screenshot 2023-11-21 at 15 15 30

**Why?**
See [issue on content repo](https://github.com/IDEMSInternational/plh-kids-app-content/issues/3). This style would likely have other general applications beyond the specified page.

**How?**
This visual style should be a new variant (see #1971 for info on "variants")

### PR DESCRIPTION
**Pull request by jfmcquade**
PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description

Adds 3 new variants for the `display_group` component: `box_gray`, `box_primary` and `box_secondary`.

Whilst there is considerable refactoring that could be done to improve the display group code, these visual variants (a grey box at least) are required for an imminent release, so the general improvements to the code are minimal.

## Git Issues

Closes #2149

## Screenshots/Videos

Updates to [feature_display_group](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1231713195)
Screenshot 2024-03-08 at 12 05 53

Screenshot 2024-03-08 at 12 06 41

### CODE REVIEW

**Review by esmeetewinkel — COMMENTED** [review]
Should be allow both `gray` and `grey`? In general I think we've favoured UK spelling

image

**Review by esmeetewinkel — APPROVED** [review]
Functional test passed

**Comment by chrismclarke** [comment]
> Should be allow both `gray` and `grey`? In general I think we've favoured UK spelling
> 

haha, was exactly my question! the difference gives soo much grief from a dev perspective, I think consensus is generally for code you should be using american version (like we do for things like `color` and `center`), but given we also want to support authors likely best to have both. Similar discussion from a while back on tailwind style library:
`https://github.com/tailwindlabs/tailwindcss/issues/521`

**Review by chrismclarke — COMMENTED** [review]
Really nice to have this typed more strongly organised in a neater way. Also the variants make a lot of sense to me. 

From a semantics perspective, using `box` to indicate that we are applying both a border and a background makes sense to me, not sure if this is a convention we've explicitly used or defined anywhere else, but could be worth generalising in the future as some sort of `generateBoxStyles` mixin that returns similar styles that can be used elsewhere (not sure if we have such use cases right now...)

**Comment by esmeetewinkel** [comment]
> (like we do for things like color and center),

Interesting you say that, the [header PR](https://github.com/IDEMSInternational/parenting-app-ui/pull/2216) that's happening in parallel uses `colour` (or does it allow both?)
image

**Comment by chrismclarke** [comment]
> Interesting you say that, the [header PR](https://github.com/IDEMSInternational/parenting-app-ui/pull/2216) that's happening in parallel uses `colour` (or does it allow both?) image

No for that one we'll be converting from `colour` in the config to `color` in the code, so yeah might be a bit confusing for anyone that uses US-English, might also be good to support both (probably converting in the parser instead of explicitly handling in the code)

**Pull request merged**
