### PR TITLE
chore: attempt fix for crlf line-endings and add clean_cache workflow

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

## Description

- Add gitattributes to try and force git to use consistent crlf line-endings
- Add workflow to make it easier to clear cached task data (side-effect of alternative approach)

## Review notes
It would be good to test if this makes a difference, if possible please:
- checkout this branch
- update current deployment (`yarn scripts deployment set`)
- sync content `yarn workflow sync`

Hopefully this should result in a cleaner output (instead of 1k file changes only those with meaningful change)

If this does not work you could also try clearing some of the git cache via:
```
rm .git/index
git reset
git status
```
And possibly try another `yarn workflow sync` after

## Git Issues

Closes #

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

### CODE REVIEW

**Comment by jfmcquade** [comment]
This seems to be working for me, I get a reasonable number of changed files
Screenshot 2022-04-20 at 13 48 45

**Comment by jfmcquade** [comment]
It seems to be working for me, I get a reasonable number of changed files.
Screenshot 2022-04-20 at 13 48 45

**Review by jfmcquade — APPROVED** [review]
LGTM

**Review by EsmeeIDEMS — COMMENTED** [review]
I'm still getting 1K+ changes, when I
1. change to early_family_maths deployment
2. sync content
3. discard all changes
4. change to plh_global deployment
5. sync content

image

When I stage them this number drops down to 27
image

**Pull request merged**
