### PR TITLE
Fix/dg style overrides

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

## Description

Rasied in [sheets comment](https://docs.google.com/spreadsheets/d/19qLXy1PF6BOH9GZ-qpcZJ3-bOfxXAgj7J8H67Nfp9MM/edit?disco=AAAAUI2xa2I), style overrides applied to display groups do not have the intended effect. This is because the overrides apply to the main container element, but for display groups most of the display logic is handled within a child div.

This PR provides a means to apply the overridden styles to a specific part of a component, and applied to display groups to allow override of flex behaviour.

This is only a temporary solution (see issue #1173), but does raise a larger challenge for when we do move to the class-based system, how best to define in the syntax a way to specify where exactly the override styles/classes should be applied. Possibly could adapt from ionic/shadow-dom concept of 'slots' and/or create a custom authoring syntax.

## Review Notes
Could impact on existing templates that use custom style overrides on display groups, have added visual test to check

## Git Issues

Closes #

## Screenshots/Videos

**Display group tiles now inherit style overrides correctly**
image

image

### CODE REVIEW

**Review by EsmeeIDEMS — CHANGES_REQUESTED** [review]
**Ignore this review, I was using a different branch.** 

I'm getting some errors when trying to run the app here, can it be that master needs to be merged in here?

**Comment by chrismclarke** [comment]
Just merged master into branch and all looking fine to me so hopefully should be working as intended.

I also realised the quick solution to get tiles to sit in the middle of each space is to used another CSS property `justify-content: space-around`. See screenshot below of updated sheet

image

**Review by EsmeeIDEMS — APPROVED** [review]
Functional test passed. @volloholic can you review code?

**Comment by chrismclarke** [comment]
I think probably good to merge. The code changes are only superficial (changing which level styles are applied to) and larger discussion of improving styling captured elsewhere

**Pull request merged**
