### PR TITLE
Perf/home page

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

## Description

- Increase the max time splash screen could be shown from 3s to 7s
- Try to defer some of startup logic until after main template displayed
- Remove unused survey package

## Review Notes
It's hard to measure what impact this will have on the specific devices (we don't have any automated timing tests), but would be good to get what feedback we can from the testers of #1283 after merge and release

As this does change the startup it would be good to do a quick functional test from a clean device for the first load (can use the appetizer link), and then closing the app and trying a subsequent load (just to ensure things like the initial splash screens display once and only once, and the templates load correctly)

## Git Issues
Progress towards #1283

## Screenshots/Videos

The package removed was a particularly bulky one (weighing in at roughly 1.4MB / 10MB for the total javascript first parsed when app loaded). This doesn't have a huge impact as the android version has all js in-built (so doesn't have to request from a server), but may help a small amount with some of the initial rendering time.

Likely larger gains would be found by removing the sheets data from being preloaded to read on demand (discussed previously with plans to migrate to individual json files instead of grouped ts files) 

image

### CODE REVIEW

**Review by volloholic — APPROVED** [review]
@chrismclarke I have approved but we should discuss the survey component at some point. I assume at some point we felt we would use this but can't remember what the decision points were.

**Comment by chrismclarke** [comment]
> I have approved but we should discuss the survey component at some point. I assume at some point we felt we would use this but can't remember what the decision points were.

@volloholic - The survey component and service were originally designed to wrap around the survey-js system for designing forms (originally user on-boarding questions), however serves little use now as we were able to extend the templating system to achieve most of what we needed short term, and long term we would be planning to create a mapping from odk -> template instead of authoring -> surveyJS -> template

The only reason why I haven't removed totally is because at the time for convenience we used the survey system as a way to show the initial fading intro slides (because the survey system was already set up to display things in full-screen at the start), but really no reason that shouldn't also be handled by the templating system (todo item that will likely need prioritising when we next want to change the slides for another app or update)

**Review by EsmeeIDEMS — CHANGES_REQUESTED** [review]
Seems to be working fine in general. I noticed that the navigation button on the organisation select template in the start up screens is no longer positioned at the bottom of the screen.

image

**Comment by EsmeeIDEMS** [comment]
I noticed also this page looks quite bad on Appetize: 
image
I'm expecting this is unrelated to this PR?

**Comment by chrismclarke** [comment]
@EsmeeIDEMS - I ran visual tests locally and all fine from the code side so I'm guessing it's an issue with the emulators themselves. At some point in the future it might be worth testing on appetizer to see what device/android version combinations gives us the best results, but for now I'll merge here and we can check once deployed live on a physical device.

**Pull request merged**
