### PR TITLE
Fix: combo box answer_list can be a data_list

### LINKED ISSUE #1966: [BUG] Answer list from data list does not work for combo box
**Describe the bug**
As commented by @chrismclarke in https://github.com/IDEMSInternational/parenting-app-ui/issues/1467#issuecomment-1214868386, answer lists for `radio_group` (and also `radio_button_grid`) components can be set by referring to a data list. This does not work for the `combo_box` component.

**App version**
v0.16.17 

**Debug Template**
[example_answer_data](https://docs.google.com/spreadsheets/d/1n82prWaYx-HWKW0ibxv-sO_Vuw9WxvuNLRJ_jI_WXtk/edit#gid=1427752706)

**Screenshots and videos**
image

### PR DESCRIPTION
**Pull request by jfmcquade**
PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description

Allows a data list to be passed as an `answer_list` parameter to a combo box component.

## Testing

This PR refactors the code for all components which take an `answer_list` parameter: `combo_box`, `radio_button_grid` and `radio_group`. Therefore, it would be good to test that each of these still works as expected, both in the case of the `answer_list` being passed as a data list, and the case of the `answer_list` passed as a string representation of a list.

## Git Issues

Closes #1966 ⚽

## Screenshots/Videos

[example_answer_data](https://docs.google.com/spreadsheets/d/1n82prWaYx-HWKW0ibxv-sO_Vuw9WxvuNLRJ_jI_WXtk/edit#gid=1427752706) working as expected, in contrast to screenshot in issue

https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/3936f063-d9cd-42d1-b06c-6ae7e4948af7

### CODE REVIEW

**Review by chrismclarke — APPROVED** [review]
Looks good to me

**Review by esmeetewinkel — APPROVED** [review]
Functional test passed. Thanks for resolving this so quickly.

**Review by esmeetewinkel — CHANGES_REQUESTED** [review]
Just encountered a bug: The parameter `placeholder` doesn't work as desired in the combo box with answer list coming from a data list. When an answer is selected and saved to the field that appears in the `value` cell, then when reloading the page the selected answer should show. Instead, we see the `placeholder` value (but displayed on the blue background).

**Comment by jfmcquade** [comment]
Thanks @esmeetewinkel, that issue should be fixed now.

I've also added an issue, #1972, to track a pre-existing bug that I noticed when looking at the code.

**Review by esmeetewinkel — APPROVED** [review]
Functional test passed

**Pull request merged**
