### PR TITLE
WIP: Show error when flow name not found

### PR DESCRIPTION
**Pull request by michaelclapham**
PR Checklist

- [ ] - Latest `master` branch merged
- [ ] - PR title descriptive (can be used in release notes)

## Description

Shows an alert when something tries to load a flow name that does not exist

### CODE REVIEW

**Comment by chrismclarke** [comment]
The implementation makes sense, although it would be good to get checks into the parser so that authors are aware without having to wait for a fail. The parser scripts already have a check from flows exist that are referenced from task flows, it would be useful if we could also have a check so that flows referenced from other flows also exist

**Comment by chrismclarke** [comment]
Happy for you to merge this once conflicts resolved and create another issue for the checks

**Review by chrismclarke — CHANGES_REQUESTED** [review]
Happy for you to merge this once conflicts resolved and create another issue for the checks as mentioned in comment above

**Comment by michaelclapham** [comment]
Closing as chat no longer used

**Pull request closed without merging**
