### PR TITLE
Feat/notification db

### LINKED ISSUE #1247: [FEATURE] Populate notification metadata domain to server
**What?**
 Populate notification metadata domain to server. In particular, we are interested in 
- sent (boolean + timestamp)
- clicked (boolean + timestamp)

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

## Description

- Add local database to track interactions with notifications
- Add API and server bindings to sync user notification interactions table
- Improve notifications debug page to track interactions and sent notifications

## Review notes
- Will require server update so after approval let me know so I can make them
- Confirm whether sent to the database is sufficient for tasks required (it is preferred not to structure the columns too strongly to align with existing campaigns as would like to keep the methods reusable, but additional fields could be populated to notification_meta field if useful)

## Author notes
The notifications debug page has been updated to include a list of sent notifications with any recorded interaction status. There is no way to know if a notification has been dismissed, but can be assumed either dismissed or blocked if notification is marked as sent but no action recorded.

## Dev notes
To try to balance general with plh/campaign-specific methods only a small subset of each notification is populated to the DB via a notification_meta column (screenshot below). 

We purposefully are not syncing scheduled notifications as these change frequently and unclear what added value they would have if list synced (would grow pretty large pretty quick, given most users may have 10-20 notifications scheduled at a time)

## Git Issues

Closes #1247

## Screenshots/Videos

Video showing notification trigger and interaction debug.
Note - sync doesn't work during part of video as I didn't have local server running (jump cuts to when corrected)
_If useful, provide screenshot or capture to highlight main changes_

https://user-images.githubusercontent.com/10515065/155465303-4e27273d-c727-4ead-9c8d-e92b1350306b.mp4

DB table created and available columns. Specific notification details are stored in the `notification_meta` column alongside more general sync/interaction info
image

### CODE REVIEW

**Review by EsmeeIDEMS — COMMENTED** [review]
Looks sensible to me. Is the `app_user_id` in this new table `(temp_...` in your video) the same as the one in the regular app_data table? We'll for sure need to relate the two. 

Is it possible to see this table somewhere in the developer tools? I'm not sure how to do a functional test.

**Comment by chrismclarke** [comment]
Yes it should be the same one (I think when running locally all ids are prefixed with `temp_`, although as these typically aren't synced to the server you should not see them).

For the functional test hopefully all the info you need should show up on the notifications debug page (i.e. list of sent notifications and track of what has been interacted with), but you can also see the table which is synced to db from the indexeddb (around 1min 30 in the video, called `local_notificaiton_interaction`)

**Review by EsmeeIDEMS — APPROVED** [review]
Functional test passed. 

Should the action "tap" be called "click"? We do call this interaction "click" when used in the campaign `action_list`.

**Comment by chrismclarke** [comment]
> Functional test passed.
> 
> Should the action "tap" be called "click"? We do call this interaction "click" when used in the campaign `action_list`.

For now I'm just passing the default action name that's provided by Android/Capacitor/Ionic, so providing anything else would require a mapping that we would manually have to keep in sync. So unless we have strong need for the change I'd say better to keep simple.

In the future we will be adding support for custom actions (e.g. action buttons from the notification) that could hold more custom interaction types

**Comment by chrismclarke** [comment]
Merging to allow server deployment and further testing

**Comment by chrismclarke** [comment]
@EsmeeIDEMS - This is now merged and deployed to the server, so if there's any additional testing required then it should be easier to do. I did just check myself, and the notification I received on the web version was synced correctly, so hopefully any notifications made following next release should also sync.

image

**Pull request merged**
