### PR TITLE
Feat/legacy code removal

### LINKED ISSUE #929: Removing hard-coded pages (from old menu)
**Details**
Until PR #923 the side menu had all its content hard-coded. The PR means that things are now templated and we should remove the hardcoded elements. The relevant files are:
1. src\app\pages\about\about.page.html
2. src\app\pages\app-terms\app-terms.page.html
3. src\app\pages\privacy\privacy.page.html
4. src\app\pages\settings\settings.page.html

Note: some of these files include functions that were there for internal functionality of the menu or its components (eg routing functions in item 4) and they all have ts and css files that will probably no longer be needed. (The reset_app function is needed as it is now an action in the app. It will probably have to be moved elsewhere if these files are being completely removed and it definitely needs to be reviewed and expanded on in the near future. I don't know any other details off the top of my head.)

### LINKED ISSUE #965: Remove old homepage (/home)
**Details**
The homepage (/home) is redundant, it is currently hardcoded to embed the template /templates/home_screen. We need the following changes:
1. Update the app routing so that / and /home redirect to /template/home_screen
2. Update the app-menu and app-back buttons so that only the menu shows on the /template/home_screen page (like the current /home ) page
3. Remove all code from /feature/home

**Screenshots and videos**
image
image

### LINKED ISSUE #1114: Remove hardcoded startup and menu pages
**Details**

- [x] The hardcoded About, Terms and conditions, Privacy policy and `analytics.survey.html` pages should be deleted as they have been replaced by templates. 
- [x] The reference to `analytics.survey.html` in the startup sequence (I believe in `home.spec.ts`) needs to be replaced by a reference to the template [accept_terms](https://docs.google.com/spreadsheets/d/1MJzzdTYDZg0VkS5zxrXY4lKV5Oi954pw1sIVJUOOzWM/edit#gid=1884781962). 
- [x] The asset `src\assets\images\privacy-policy.svg` can be deleted, since it is now uploaded to the Google Drive [here](https://drive.google.com/file/d/1mDThp4VXDioUE4boMmsBaCf9JTUewS0p/view?usp=sharing). 
- [x] Add a redirect so that the URL /privacy displays the template [app_menu_privacy_policy](https://docs.google.com/spreadsheets/d/1NUCgonMc3K4y9bFjYH7LjquRZyiIN2AappLP_0mlH5Q/edit#gid=484038577). This is to ensure that the link to the Privacy Policy in the Google Play Console keeps working. 

**Screenshots and videos**
image
image

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

## Description

To help with reducing bundle sizes and to give a cleaner base for upcoming multi-repo apps, a large clearing has been done of the majority of legacy assets and features. As none of these features has been in use since moving to the templating system, It is recommended as better to just remove from the repo, and if for any reason requiring re-implementation in the future restore from git archive.

Overall reduction is about 10MB (7%) of assets, and 1MB (17%) core code bundle

**Packages**
- angular material (previously used for event calendar editor)
- chartjs (never used)
- fullcalendar (previously used for event calendar), 

**Features**
- Calendar (not used, implementation incomplete)
- Module Page (replaced by templates)
- Take-a-pause (replaced by templates)
- Conversation (not used, requires major refactor)
- Gallery (not used, implementation incomplete)
- Tips (replaced by templates)
- Goals (not used, implementation incomplete)
- Home screen (replaced by templates)
- Care packages (replaced by templates)
- Parent points (replaced by templates)
- Animations (never used, Michael testing (?))
- Settings (replaced by template except for app reset method which has been refactored to shared service)
- Template-testing (this is the main placeholder page to load templates, so has just been renamed to template-page)

**Template Components**
- css_anim (not used anywhere and pretty sure was replaced by lottie animations)

**Assets**
Removed all hardcoded assets with exception of those still currently imported directly from components (screenshot below for search used). This mostly just consisted of:
- icons used by audio player and timer
- splash screen images and logos used in hardcoded splash survey
- privacy policy and sync images used in hardcoded analytics/welcome survey

**Other changes**
- Refactor home page route to read a `HOME_SCREEN_TEMPLATE` constant from the `data-models/contants` package instead of previously hardcoded routes.
- Fix issue where back button would still appear on home_screen template

## For Authors
- I've done my best to manually test all links from main pages I can find, and will run the visual test against also. Additional manual testing is recommended for things that aren't captured in the static pages (e.g. popups)

- I've left the hardcoded about, privacy policy and app-terms pages, however I think they have been replaced with templates. One additional check that should be done is whether any of these links are used directly elsewhere (e.g. the play store app listing requires a fixed privacy policy which may be one of these. Once confirmed/resolved will remove (can always add as a redirect to keep the URL at /privacy displaying the template)

## For Developers
Most of the legacy/deprecated code has been or could be replaced by the templating system and is unlikely to have any use in the future (better re-implemented with templates). 

The one exception I can currently think of is the chat/conversation system, which is highly custom and would likely remain a standalone module if re-introduced. Nonetheless, it has been removed from the current system as a) The code is no longer functional following a number of previous refactors, and b) It includes over 5MB or related assets, animations etc.

So it is recommended to keep an internal note if wanting to re-implement, to check out the code from `v0.12.5` or lower.

## Git Issues

Closes #965
Closes #1114
Closes #929

## Screenshots/Videos
**Required assets (remaining), all others deleted**
image

**Before**
image

**After** Bundle size around 10MB smaller
image

### CODE REVIEW

**Comment by chrismclarke** [comment]
Checked diffs below and all look fine to me (false-positive)
```
1 | 25.1% | example_lang_template_1
2 | 18.8% | example_changed_action
3 | 13.3% | debug_field_null_2
4 | 4.2 % | debug_radio_group_size
5 | 1.5 % | example_calc_2
```

**Comment by EsmeeIDEMS** [comment]
About template: [app_menu_plh](https://docs.google.com/spreadsheets/d/1NUCgonMc3K4y9bFjYH7LjquRZyiIN2AappLP_0mlH5Q/edit#gid=500877329)
Terms and conditions template: [app_menu_terms](https://docs.google.com/spreadsheets/d/1NUCgonMc3K4y9bFjYH7LjquRZyiIN2AappLP_0mlH5Q/edit#gid=971861890)
Privacy policy template: [app_menu_privacy_policy](https://docs.google.com/spreadsheets/d/1NUCgonMc3K4y9bFjYH7LjquRZyiIN2AappLP_0mlH5Q/edit#gid=484038577)

Before removing the corresponding hardcoded pages, we should template the page on the screenshot below. This page seems to refer to the hardcoded Terms and Conditions / Privacy Policy pages, rather than the templates. 
image

**Review by EsmeeIDEMS — APPROVED** [review]
Functional test passed.

**Comment by EsmeeIDEMS** [comment]
Does this close issue #965?

**Comment by chrismclarke** [comment]
@EsmeeIDEMS - I've now added a few extra configurations and code-bindings to help address some issues references (still need to update handling of analytics survey)

image

**Comment by EsmeeIDEMS** [comment]
When the template [accept_terms](https://docs.google.com/spreadsheets/d/1MJzzdTYDZg0VkS5zxrXY4lKV5Oi954pw1sIVJUOOzWM/edit#gid=1884781962) is launched as part of the startup sequence, the buttons that should `go_to` a template don't work. When clicking either of the two blue buttons, the hyperlink does change but the template does not show.

https://user-images.githubusercontent.com/74557272/145412997-aa1e0dce-c298-41ac-84c8-0f4476eb1464.mp4

I've now replaced the actions by `pop_up`, which works better (although top of the screen, where the header usually is, does not get grayed out) 
image

(N.B. for the button texts to display correctly you need to update the globals)

**Review by volloholic — APPROVED** [review]

**Pull request merged**
