### PR TITLE
Feat: Add PLH Facilitator MX theme

### PR DESCRIPTION
**Pull request by esmeetewinkel**
PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description

Attempt to create a specific theme for the PLH Facilitator MX deployment, using the partner's branding colours. 

I followed the changes made in the PR creating the PfR theme #2167
image

@jfmcquade I was wondering what decides that the text on the header and buttons shows in black rather than white? 
image

## Git Issues

Closes https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/issues/53

### CODE REVIEW

**Comment by chrismclarke** [comment]
In case of interest, a quick look at [webaim contrast checker](https://webaim.org/resources/contrastchecker/) gives the following scores for accessibility

image

If using white as the contrast color we get
image

So in either case I think the black text gives better results (passes AA standard, not AAA). Tweaking the primary color slightly (e.g. `#48A3A8`) gives a contrast ratio a little better than 7:1 (which is the threshold for AAA)

image

**Comment by jfmcquade** [comment]
Thanks @chrismclarke, great to know about those resources.

@esmeetewinkel: in terms of what actually decides, there is a utility function in the file `src/theme/themes/utils/contrast-colour.scss` that runs some maths to decide whether the contrast colour should be black or white. 

I haven't looked into the details, but as it says in the comment at the top of the file, the code is taken from [this post](https://sgom.es/posts/2016-12-21-using-sass-to-automatically-pick-text-colors/). The algorithm tries to maximise the contrast ratio, as defined by the WCAG standards that Chris referenced.

Screenshot 2024-04-03 at 16 21 30

**Comment by esmeetewinkel** [comment]
Opted for partner colours blue and orange (not too different from the default theme) for improved contrast. 
Before / After: 
image

image

**Comment by esmeetewinkel** [comment]
See this content PR https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/pull/57 for test preview link

**Review by jfmcquade — APPROVED** [review]
Good job figuring out what to change, it looks good to me.

> NB. I thought this round and rectangular button had the same colour, but in this changed theme it is apparent that they are slightly different. Maybe they should be the same? To me the difference doesn't look intentional. @jfmcquade

Good spot. The issue is that one of the buttons has colour `--ion-color-secondary` (via a theme-customisable property `--button-background-secondary`), whilst the other has colour `--ion-color-secondary-400`. Because of the way our colour generating system works, there will always be one colour "weight" that closely resembles the input `secondary` colour, and therefore may appear oddly similar. This will vary depending on the relative lightness of that original input colour, so it's a bit hard to account for cases like these. 

In this instance, I'm pretty sure this could be fixed by removing the `style: orange` parameter in cell E43 of the [parent_profile](https://docs.google.com/spreadsheets/d/1VQTZglKW0oRPXxncnDyix_s9EfGBSZ4intIaIeXu798/edit#gid=1729633565) template. The `orange` parameter is outdated anyway (as the secondary colour could be anything, there are still a handful of variables so-named), and without it the button's background should default to the value of `button-background-secondary` as specified by the theme.

**Comment by esmeetewinkel** [comment]
I'm finding that without the orange parameter the button becomes blue (primary)...

image

**Comment by jfmcquade** [comment]
> I'm finding that without the orange parameter the button becomes blue (primary)...

Ah sorry, you're right. There is no default secondary option. Setting the `style: get_me_going` should work for now (although not very nice). I could make a quick PR to add a `style: background-secondary` option

**Comment by esmeetewinkel** [comment]
Hahaha I had forgotten about that style naming...

I found that the `style: navigation` round button does have the colour I want, only that it's slightly smaller (not a problem) so I'll use that for now.

image

**Pull request merged**
