### PR TITLE
accordion changes

### PR DESCRIPTION
**Pull request by AndriiHubarievW**
PR Checklist

- [ ] - Latest `master` branch merged
- [ ] - PR title descriptive (can be used in release notes)

## Description
Draft PR for accordion. 

1.  ability to toggle state of a section (open | close).
2. smooth animation for open and close.
3. ability to pass any template in a section.
4. progress bar.
5. hidden progress bar when section is open.

Снимок экрана 2021-04-05 в 18 52 32
Снимок экрана 2021-04-05 в 18 52 45

_What this PR does_

## Git Issues

_Closes #_

## Screenshots/Videos

_If useful, provide screenshot or capture to highlight main changes_

### CODE REVIEW

**Comment by AndriiHubarievW** [comment]
https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=391959604 
Spreadsheet link

**Review by michaelclapham — CHANGES_REQUESTED** [review]
This is looking good, but it would be nice if the area you can click to expand and contract the accordion was a bit taller.

At the moment each section expands and collpases if you can click on the heading (the h2), but could we get it to also expand if you click on the margin area on the top and the bottom of the header? (The orange area above and below the h2 Description of week 1 in this screenshot)

image

**Comment by AndriiHubarievW** [comment]
> This is looking good, but it would be nice if the area you can click to expand and contract the accordion was a bit taller.
> 
> At the moment each section expands and collpases if you can click on the heading (the h2), but could we get it to also expand if you click on the margin area on the top and the bottom of the header? (The orange area above and below the h2 Description of week 1 in this screenshot)
> 
> image

**Comment by AndriiHubarievW** [comment]
Sure. I can switch margin to padding in order to achieve behavior you expect. 
Снимок экрана 2021-04-06 в 12 16 50

**Review by smborio — APPROVED** [review]
Still need to investigate impact of ng-deep h2. Otherwise it looks ok.

**Pull request merged**
