### PR TITLE
Add select text feature for user code

### LINKED ISSUE #1006: [FEATURE] Copy-to-clipboard component
**18/07/2022 Reopened - see [comment below](https://github.com/IDEMSInternational/parenting-app-ui/issues/1006#issuecomment-1187596203)**

**What?**
A new component _select_text_ (i.e. the _type_ in the spreadsheet) to display a text and a copy-to-clipboard button (with an icon _copy_icon_ or a text _copy_text_). When the copy-to-clipboard button is clicked, the text input in the _value_ column is copied to the clipboard, and the button is replaced by the text _copied_text_ or an icon _copied_icon_. As usual, icons should be coming from the [plh_assets](https://drive.google.com/drive/folders/1dp9QAQ84m8pm0IBQTSPXe1ramyynKPNn) folder on the Google Drive, or from the icon library [Ionicons](https://ionic.io/ionicons). 

**Why?**
With this feature, users can more easily copy their UUID from the template [user_code](https://docs.google.com/spreadsheets/d/1yb7SP-W-uOvxDRELlLJEDPwPFE9H1GtEHsn2_sVZtAs/edit#gid=1384726662) (currently they are taking a screenshot of the page).

image

**How?**
Syntax proposed in template [feature_select_text](https://docs.google.com/spreadsheets/d/1MX-sy4RLy7xPkl0vHZ0lfp-kzGWyohViWjNhyGn7Vts/edit#gid=1254547698).
image

**Other details**
I'm thinking of something like this 
react-copy-to-clipboard-demo2
There's no design for this component. I'd suggest the text and button appear in a dashed box with look-and-feel similar to the display_group style _dashed_box_. For user-friendliness it would be good if the clickable button is not just an icon, but actually looks like a button (e.g. has a drop-shadow).

### PR DESCRIPTION
**Pull request by thisishamza**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

## Description
With the "select_text" feature, content can now be copied on the web.

## Git Issues

Closes #1006

### CODE REVIEW

**Comment by zulkifelff** [comment]
This PR is without the Yarn Update. 

@thisishamza , Merge Master branch in it and test locally.

**Review by chrismclarke — APPROVED** [review]
Thanks for tidying up the PR @thisishamza 

Apologies it's taken so long to review (I had been given other prioties for the project).

I think the code is fine and works well enough for me. I've made a few minor changes to replace the ionic-native clipboard library with the capacitor one (as we've slowly been moving all our dependencies from ionic to capacitor, which are the same company). I also fixed retrieval of image assets and made one minor style fix (changes visible in added commits)

Otherwise I'd say good to merge but I'll let @EsmeeIDEMS make a final test

**Review by EsmeeIDEMS — CHANGES_REQUESTED** [review]
This  seems to have knock-on effects on the nav buttons, the padding between the back and forward buttons is lost (first screenshot on `master `branch, second screenshot on `copy-to-clipboard`)
image
image

**Comment by chrismclarke** [comment]
> This seems to have knock-on effects on the nav buttons, the padding between the back and forward buttons is lost (first screenshot on `master `branch, second screenshot on `copy-to-clipboard`)

More confusion related to keeping PRs up-to-date with master I'm afraid. The nav spacing issue was one that we resolved in another PR, however existing PRs do not automatically sync updates to master (they need to be manually pulled), and annoyingly git only shows you that they are not in sync in the case of conflicts.

I've just merged master changes and pushed.

**Comment by chrismclarke** [comment]
Approved on call, merging

**Pull request merged**
