### PR TITLE
Fix: iOS fullscreen popups extend outside safe area

### LINKED ISSUE #2263: [BUG] iOS: Full screen pop-up intersects native device status bar
**Describe the bug**
When testing an iOS app on the emulator (e.g. [FacilitatorApp Mexico](https://appetize.io/app/sqd4ghzfbdq5n7cerawfr32yim?device=iphone14pro&osVersion=16.2)), the full screen pop-ups intersect the native device status bar.

**To Reproduce**
Launch the app on Appetize, the first few screens (e.g. language select) are full screen pop-ups.

**Screenshots and videos**
image

### PR DESCRIPTION
**Pull request by jfmcquade**
PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description

Previously on iOS, fullscreen popups would not respect the device "safe area", meaning that the content overlapped with the device status bar (and notch/punch-out if present) at the top of the screen.

I've manually uploaded an iOS build of the PLH Facilitator MX app, using this PR's feature branch, to appetize [here](https://appetize.io/app/mwyz2tx457dv55dw4eye4z2dpi?device=iphone14pro&osVersion=16.2).

## Dev notes

It's worth noting that this issue is due to the fact that only the [ion-footer](https://ionicframework.com/docs/api/footer) and [ion-header](https://ionicframework.com/docs/api/header) with toolbars inside them will automatically account for the device safe area. This grants flexibility, but means we need to manually account for the safe area when the header and footer are omitted. 

For reviewing: the [first commit](https://github.com/IDEMSInternational/parenting-app-ui/pull/2271/commits/b597ccfec9a57580c2b65f7c914c776d5f94be0b) refactors the popup component code into a folder, look at the [second commit](https://github.com/IDEMSInternational/parenting-app-ui/pull/2271/commits/db7a2806069c944c286675cdba0e3d0597f75d13) for meaningful code changes.

## Git Issues

Closes #2263

#### iPhone 15

https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/cd6d55de-a257-4b63-bed1-6083c6f970b4

#### iPhone 8 Plus

https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/d38285c0-6608-4e6d-9c25-42adc79e3af7

#### iPhone 15

https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/88efabf6-220b-4a05-bd19-cecdd47cdb1b

#### iPhone 8 Plus

https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/7e95d94d-bd57-45c1-af87-bc0efc6ce0cc

### CODE REVIEW

**Review by chrismclarke — APPROVED** [review]
Git has done a pretty bad job of tracking diffs here - thanks for splitting the commits at least so I can still mostly follow the style changes from db7a280.

As a tip for next time, if planning to both rename and modify a file you could try manually using cli to `git mv` the files that it tracks a bit better. As for the styles, not sure why it doesn't like the inline diffs, although might have been better to put the `&[data-fullscreen]` block a bit less nested, e.g. `.popup-backdrop[data-fullscreen]`

But otherwise looks good to me

**Review by esmeetewinkel — APPROVED** [review]
Great! I agree this resolves the issue of the full screen pop up intersecting the status bar. 

The close button on a regular pop-up (in front of a full screen pop up) annoyingly does still intersect the device status bar. This makes the pop up a bit difficult to close (I think it restricts the clickable area to an area outside the status bar). 
image
Shall I create a follow up issue for this?

**Comment by jfmcquade** [comment]
> The close button on a regular pop-up (in front of a full screen pop up) annoyingly does still intersect the device status bar. 
> ...
> Shall I create a follow up issue for this?

Thanks, I'll see if it's quick to resolve and can be included in this PR

**Comment by jfmcquade** [comment]
@esmeetewinkel I've pushed [a commit](https://github.com/IDEMSInternational/parenting-app-ui/pull/2271/commits/2a891faa273bbffbde4cd869443abe7dad03bf48) which should fix the non-fullscreen popup issue. I've updated the [appetize link](https://appetize.io/app/mwyz2tx457dv55dw4eye4z2dpi?device=iphone14pro&osVersion=16.2).

## Debug deployment

https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/74f23a71-4b58-459e-bf37-1a77e80cc17d

## Facilitator deployment

https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/aed762d6-0661-4724-a96f-5aaaa657fb6c

**Review by esmeetewinkel — APPROVED** [review]
Thanks Johnny, looks good.

**Pull request merged**
