### PR TITLE
Feat/assets theme lang alt

### LINKED ISSUE #1798: [FEATURE] Handle theme and language assets
From #1526 
> - We want translation-specific assets and theme-specific assets to be as independent as possible
> - Currently, if a translated version of an asset exists, this will be used regardless of theme-specific versions
>   - This is fine for our current use case, as we only have images for the second ("professional") theme, which do not have translated versions – all of the assets for the professional theme sit inside a "global" subfolder
>   - But more work is needed to handle cases where translated, theme-specific assets exist, i.e. to handle language-code subfolders inside the professional theme folder.

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [ ] - Latest `master` branch merged
- [ ] - PR title descriptive (can be used in release notes)

## Follow-up tasks (to create issue)
- [ ] Update documentation
- [ ] Sync content (will update assets contents)

## Description
Builds from #1795

> This PR adds the functionality to override assets with a variation relating to the current theme and language, including a combination thereof (e.g. a translated version of an asset that differs based on theme).
> 
> If a variation of the requested asset for the current theme and language does not exist, then a different version of the asset will be returned as a fallback. The order of priority for these fallbacks is:
> 1. current theme, current language
> 2. default theme, current language
> 3. current theme, default language
> 4. default theme, default language

**Main Changes**
- Treat assets in top-level folders as global, even if no named global folder
- Provide more flexibility for theme and language folder nesting.  Now language or theme folders can be placed in any directories and used to provide overrides at the current level. E.g. to override for both theme and lang

**Source**
`global/nested/img.jpg`

**Before**
`theme_professional/tz_ke/nested/img.jpg`

**After**
`theme_professional/tz_ke/nested/img.jpg`
`nested/tz_ke/theme_professional/img.jpg`
`nested/theme_professional/tz_ke/img.jpg`
`tz_ke/theme_professional/nested/img.jpg`

Or any path that will resolve to the same filename (ignoring global prefix) `nested/img.jpg`, once the theme and language segments of the path have been removed

**Additional Changes**
- Refactor tests to use more explicit per-test file and folder structures
- Track relative filepaths in override contents to support more varieties of folder structure

## Review Notes
Will need to sync content to populate assets in updated format and view changes

## Dev Notes
Formatting of asset contents slightly changed, now default theme/language not nested, `themeVariations` renamed to `overrides`, and additional filepath included for assets that sit in a location not identical to the entry name (e.g. language/global/override assets)

image

## Git Issues
Closes #1795
Closes #1798

## Screenshots/Videos
**Demo**

[ParentApp (2).webm](https://user-images.githubusercontent.com/10515065/230375577-dc3a39db-9d22-4c2c-b08c-1baa56649208.webm)

### CODE REVIEW

**Comment by esmeetewinkel** [comment]
@volloholic wanted to discuss this when we meet next.

**Comment by chrismclarke** [comment]
> @volloholic wanted to discuss this when we meet next.

@esmeetewinkel - it would be good to clarify if this should be blocking merge or not. 

I'm aware the original PR from @jfmcquade is now about 2 months old and will start having conflicts with work on the remote assets system, so if possible would still be good to get your testing and see if we can look to merge this and address future discussion points in follow-up

**Comment by volloholic** [comment]
Agreed you have captured that correctly I am not opposed to merging.

**Comment by jfmcquade** [comment]
I've committed a version of the assets `contents.json` that reflects the format produced by the assets processor on master, so that a proper comparison can be made when reviewing this PR (previously I had committed the contents file that was generated using the WIP processor that appeared in #1795)

See updated comparison:
Screenshot 2023-04-14 at 11 17 41

**Review by jfmcquade — APPROVED** [review]
Looks good to me. The code is clear.

To test the new ambivalent folder structure feature, I added a test image to the gdrive folder [here](https://drive.google.com/drive/folders/1FrXpDy0lvskGjY10cKfOruGZZH8o3kQO?usp=share_link), `tz_sw/quality_assurance/theme_professional/`, and it is saved correctly to the assets contents file by the new processor:
Screenshot 2023-04-14 at 12 25 49

**Review by esmeetewinkel — COMMENTED** [review]
1. I had understood from this that the top-level `global` assets folder would no longer be necessary. I tested this by creating a folder `quality_assurance` parallel to the `global` folder and putting some assets in it, however, I'm getting this error when syncing assets. 
image
Placing an image directly parallel to the global folder did sync correctly (only that the "filePath" entry is missing in the contents.json, but I'm guessing that is because it is not nested)
image

2. I tested out what happens when there are multiple assets that, after stripping out the language and theme folders, end up with the same file path. It seems that, although the files themselves do appear, the file name does not appear in the `contents.json` file at all. The console gives no warning indicating that this problem is occuring. 
image

**Comment by chrismclarke** [comment]
Thanks @esmeetewinkel - turns out those errors were being triggered from our manual quality checks which are no longer needed. They didn't show up in the tests as the error logging mechanism had been surpressed (to allow tests to pass that expected errors, i.e. checking our QA tests worked), although I've tidied up the code to only surpress the errors when explicitly required.

> 1. I had understood from this that the top-level `global` assets folder would no longer be necessary. I tested this by creating a folder `quality_assurance` parallel to the `global` folder and putting some assets in it, however, I'm getting this error when syncing assets.

Should now work as I've removed the QC check for global assets folder (no longer required)

> 2. Placing an image directly parallel to the global folder did sync correctly (only that the "filePath" entry is missing in the contents.json, but I'm guessing that is because it is not nested?)

This is expected, the filepath property only populates if it is different than the path provided in the entry key. So it occurs for things like lang/theme overrides (including global folder), but not for regular paths.

> 3. I tested out what happens when there are multiple assets that, after stripping out the language and theme folders, end up with the same file path. It seems that, although the files themselves do appear, the file name does not appear in the `contents.json` file at all. The console gives no warning indicating that this problem is occuring.

Thanks for flagging this one, I'm not sure why nothing appears, it might be a case that the original file is not listed - but I hadn't considered the case where the overrides resolve to the same file. I've added an explicit QC check and test for this now, which should throw an error as below:
image

I also found an issue with the asset filter functions (where it would only look at the first folder name) which could be related. I've now fixed so if possible could you run your tests again?

**Review by esmeetewinkel — COMMENTED** [review]
Since your the changes I'm now no longer able to sync assets into this branch, see error below

image

**Comment by chrismclarke** [comment]
> Since your the changes I'm now no longer able to sync assets into this branch, see error below

Thanks @esmeetewinkel - I think there was an issue handling deployments which don't specify any language filters. I've added an extra test for this case and fixed the code so hopefully should be working now as expected

**Review by esmeetewinkel — CHANGES_REQUESTED** [review]
When running the app on this branch (`plh_global` deployment) none of the assets are found - not for default or other language nor for professional or default theme. 

image

In the example of the screenshot, the image file path on this branch shows as 
`assets/app_data/assets/plh_images/workshops/w_self_care/tools.svg` as opposed to `assets/app_data/assets/theme_professional/global/plh_images/workshops/w_self_care/tools.svg` on the master branch.

**Review by esmeetewinkel — APPROVED** [review]
Functional test passed, after doing a content sync assets are working correctly.

**Pull request merged**
