### PR TITLE
Core/capacitor 5

### LINKED ISSUE #2038: [Android] - Update to Capacitor 5
**Details**
Mentioned in #1862 but just to make a more explicit issue, capacitor 5 has been out for a while now, upgrade notes below
https://capacitorjs.com/docs/updating/5-0

**Screenshots and videos**
_If applicable, add screenshots or videos to help explain your issue._

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description

Update capacitor core 4->5
Apply changes as outlined in https://capacitorjs.com/docs/updating/5-0

## Git Issues

Closes #2038
Closes #1862
Closes #2037

## Dev Notes
A number of settings have been migrated, including how android id gets populated as part of `build.gradle`. When syncing to branches that have hardcoded overrides will need to be careful to make sure changes are migrated also

**Plugin updates**
[Device](https://capacitorjs.com/docs/updating/5-0#device)
Plugin changes name of `uuid` -> `identifier`. I'm not aware of any changes to how this property is populated, so hopefully things should continue to work as expected (have remapped the variable name in our code to stick with uuid). Would be good to confirm a test user retains same uuid before and after update

[Local Notifications](https://capacitorjs.com/docs/updating/5-0#local-notifications)
States that permissions have to be requested for Android 13, however we already had code to request permission for web so I don't think any additional changes required. I've added a couple short lines of code just to return permission state immediately if already granted. Ideally we should also follow a similar pattern for push notifications, however as these are not currently in use I haven't made any updates

## Review Notes
Need to test on Android 13 device, specifically:
- Native functionality works (e.g. firebase login, local notifications)
- UUID works as expected

I've tried testing on an Android 13 emulator, notification permission popup did work although even after accepting the notifications debug page didn't show as enabled. It appeared to take a full app restart before working as correctly (could manually send notification from campaign page, and enabling debug notification campain listed in notification page). Not sure if this is an emulator or code issue, so would be interesting to see if other people get the same result.
 
I also tried rejecting the permission and everything seemed to work as expected, with the notification page allowing me to re-prompt after pressing the bell icon

I've updated the debug deployment to include an [example_google_auth](https://docs.google.com/spreadsheets/d/12xo0ewDN0bbeVrs3klWd9J8DkFQLTCYX1zhGWnovqIo/edit#gid=579616705) template, and updated the [navigation](https://docs.google.com/spreadsheets/d/10J1z1F9TA0N72ySpLfw7RojoB1SG5a4_RDj8_q86VcU/edit#gid=575534568) template to include links to notification page for testing

## Screenshots/Videos
Popup seen on Android 13 launch
image

### CODE REVIEW

**Review by esmeetewinkel — COMMENTED** [review]
I've tried testing this on Appetize by going to settings -> developer mode -> pw app_dev to reveal the notifications button in the side menu. Notifications only occasionally come through to the device, but in my tests this was both the case on Android 13 and Android 12. 

Maybe @jfmcquade can do more accurate testing on local Android emulator.

**Comment by jfmcquade** [comment]
### Migration steps

Referring to the [migration guide](https://capacitorjs.com/docs/updating/5-0) and inspecting the code changes, all relevant steps seem to have been followed correctly.

As stated in the [docs](https://capacitorjs.com/docs/updating/5-0#upgrade-android-studio), I updated my version of Android Studio (to the latest, `2022.3.1 Patch 1`). I also ran the `AGP Upgrade Assistant` as recommended in that section. Doing so bumped the gradle version number [here](https://github.com/IDEMSInternational/parenting-app-ui/pull/2046/commits/b5d54ec620e1349a4e93ae29cc2a59524d393441#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65a), which I've committed.

### Local notifications

Testing natively (Pixel 5, Adndroid 13) using a bundle uploaded to [internal app sharing](https://play.google.com/console/u/1/internal-app-sharing/?pli=1), I get the prompt requesting notifications permission on fist app launch. 

Screenshot 2023-08-22 at 13 56 21

Then there is some slightly strange behaviour, the most common being as follows:
The debug notifications do not come through when triggered "send now" the first time. But if you click "send now" again, in the window of time before the debug notification is removed from the list, then the notification comes through immediately, followed by a second notification that comes through when the second timer has completed. This behaviour is present when running natively and also when running on appetize. However, looking at an older appetize build for the plh_global deployment, the issue is also present there, so it seems to be a legacy issue affecting notifications (possibly only notifications triggered manually from the notifications page?). See videos below.

#### Native

https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/72ec61fc-3b57-4867-bf5e-83b61e728f8c

This was by far the most common behaviour I've observed, however occasionally (seemingly more likely straight after relaunching the app), a notification would come through immediately as expected.

#### Appetize PR Build

Following the appetize link associated with this PR, with the emulator settings changed to run Android 13 on a Pixel 7, I observed the same behaviour as testing natively.

https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/3de6d237-c50d-4ad8-8b75-0ff518d075b4

One time out of around 6 rounds of testing, the notifications did work as expected, recorded here:

https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/7a5be976-163a-4013-a726-bc68634db2e7

#### Appetize Legacy Build

Using [this appetize](https://appetize.io/app/2kb2kp5jsot6be66r7vvlcywrq?device=pixel7&osVersion=13.0&scale=75) link for a pre-existing build of the `plh_global` branch, I found that the same bug was present.

Pixel 7, Android 13:
https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/1e4f8568-fbc0-45f7-8cb1-faaa2a21600b

Pixel 4, Android 12:
https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/16c4c025-8e96-4c7e-83c2-f04f85bcaa75

So this appears to be a legacy issue, but one that we should prioritise fixing

### Google Auth with Firebase

Using the new [example_google_auth](https://docs.google.com/spreadsheets/d/12xo0ewDN0bbeVrs3klWd9J8DkFQLTCYX1zhGWnovqIo/edit#gid=579616705) template, the functionality seems to work as expected on native Android 13.

https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/f3fa2cd8-6e70-4f63-ac46-2c22dd9bd7d8

[Previously](https://github.com/IDEMSInternational/parenting-app-ui/pull/1862#issuecomment-1686650116) the login would fail, causing the app to freeze and logging [this error](https://app.glitchtip.com/idems/issues/2722244/events/4fcdcb34b76f45e98f8f8671379d85cc) to glitchtip. [No such errors](https://app.glitchtip.com/idems/issues?project=2438) are being logged for the debug app generated from this PR.

**Comment by chrismclarke** [comment]
@esmeetewinkel @jfmcquade 
Thanks for the in-depth reviews. Just to confirm, do we know if the current notification behaviour is different to the PR? Is this a new issue created with the capacitor 5 update (and hence should block merge), or a newly identified legacy issue that we should create a new PR for (following merge here)?

**Comment by jfmcquade** [comment]
Good point, I was a bit ambiguous in my review.

I've just made made a build from `master` and can confirm that the notifications bug *is* present there too when I run on my phone (Pixel 5, Android 13). So it is a pre-existing bug and we should be good to merge this PR and handle it separately, I'll make an issue.

I have also now tested the native in-app update functionality on a build from this PR's feature branch (following the steps outlined in #1803), and can confirm it seems to work as expected (new template for testing in-app update added [here](https://docs.google.com/spreadsheets/d/1H6VhPmnxOIV5tw9p4XbVYS0tfNU3M7KZzgH9GmomNPI/edit#gid=1682302917)).

https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/c278f460-2ea8-403e-9420-fc3fef4c2e6e

**Review by jfmcquade — APPROVED** [review]

**Comment by chrismclarke** [comment]
Thanks for diving deeper into this @jfmcquade and adding the follow-up issue. Are you happy to merge here @esmeetewinkel or do you think we should try get the related issue resolved first and then come back and test again?

**Comment by esmeetewinkel** [comment]
>Are you happy to merge here @esmeetewinkel or do you think we should try get the related issue resolved first and then come back and test again?

Happy to merge this now.

**Pull request merged**
